# Generated by Django 6.0.7 on 2026-07-27 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('capacidad_kg', models.FloatField(default=1000)),
                ('personas', models.PositiveIntegerField(default=1)),
                ('viajes_max', models.PositiveIntegerField(default=1)),
                ('plantel_lat', models.FloatField(blank=True, null=True)),
                ('plantel_lon', models.FloatField(blank=True, null=True)),
                ('canton_asignado', models.CharField(blank=True, default='', max_length=200)),
                ('distrito_asignado', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, default='', max_length=500)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('peso_kg', models.FloatField(default=0)),
                ('canton', models.CharField(blank=True, default='', max_length=200)),
                ('distrito', models.CharField(blank=True, default='', max_length=200)),
                ('camion_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos', to='rutas.camion')),
            ],
        ),
    ]
