# Generated by Django 6.0.7 on 2026-07-27 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('velocidad_kmh', models.PositiveIntegerField(default=40)),
                ('tiempo_parada', models.PositiveIntegerField(default=10)),
                ('tiempo_descarga', models.PositiveIntegerField(default=30)),
                ('usar_almuerzo', models.BooleanField(default=False)),
                ('hora_almuerzo_inicio', models.TimeField(default=datetime.time(12, 0))),
                ('hora_almuerzo_fin', models.TimeField(default=datetime.time(13, 0))),
                ('tope_horas_jornada', models.FloatField(default=8.0)),
                ('velocidad_variable_via', models.BooleanField(default=False)),
                ('velocidad_rapida_kmh', models.PositiveIntegerField(default=40)),
                ('balancear', models.BooleanField(default=False)),
                ('depot2_lat', models.FloatField(default=9.964356)),
                ('depot2_lon', models.FloatField(default=-84.161528)),
            ],
        ),
    ]
