# Generated by Django 6.0.7 on 2026-07-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_configuraciongeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_json', models.JSONField(blank=True, null=True)),
                ('modo_calculo', models.CharField(blank=True, default='', max_length=100)),
                ('calculado_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutaFrecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=300, unique=True)),
                ('dias', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
