# Generated by Django 6.0.7 on 2026-07-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_resultadocalculo_rutafrecuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.FloatField(default=0)),
                ('vida_util_anios', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CostoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('administrativa', 'Administrativa')], max_length=20)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.FloatField(default=0)),
                ('frecuencia', models.CharField(choices=[('Día', 'Día'), ('Semana', 'Semana'), ('Mes', 'Mes'), ('Año', 'Año')], default='Mes', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CostosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ton_actual', models.FloatField(default=0)),
                ('precio_ton_actual', models.FloatField(default=0)),
                ('ton_nuevo_manual', models.FloatField(blank=True, null=True)),
                ('horas_laboradas', models.FloatField(default=8.0)),
                ('precio_hora', models.FloatField(default=0)),
                ('rendimiento', models.FloatField(default=5.0)),
                ('precio_litro', models.FloatField(default=0)),
                ('costo_km_extra', models.FloatField(default=0)),
            ],
        ),
    ]
