# Generated by Django 6.0.7 on 2026-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_costoinversion_costorecurrente_costosgenerales'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedPropiaGrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodos_json', models.JSONField(blank=True, null=True)),
                ('aristas_json', models.JSONField(blank=True, null=True)),
                ('n_lineas', models.IntegerField(default=0)),
                ('n_componentes', models.IntegerField(default=0)),
                ('tamano_componentes_json', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RedPropiaPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RedPropiaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TasaViaKgKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique=True)),
                ('kg_extra_por_km', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ViaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados_via_json', models.JSONField(blank=True, null=True)),
                ('tramos_mapa_json', models.JSONField(blank=True, null=True)),
                ('sumar_a_recoleccion', models.BooleanField(default=False)),
                ('detalle_progresivo_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
