# Generated by Django 6.0.7 on 2026-07-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_alter_camion_capacidad_kg_alter_camion_personas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamionDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_camion', models.CharField(max_length=200, unique=True)),
                ('dias', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='resultadocalculo',
            name='dia',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
