# Generated by Django 6.0.7 on 2026-07-29 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_camiondisponibilidad_resultadocalculo_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='porcentaje_relleno',
            field=models.FloatField(default=5.0, help_text='% del peso diario que sale contaminado y va a relleno sanitario en vez de a Planta San Antonio.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='relleno_lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='relleno_lon',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
