# Generated by Django 6.0.7 on 2026-07-29 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0008_configuraciongeneral_porcentaje_relleno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tiempo_lavado',
            field=models.PositiveIntegerField(default=20, help_text='Minutos de lavado del camión al final de la jornada.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
