# Generated by Django 6.0.7 on 2026-07-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_configuraciongeneral_tiempo_lavado'),
    ]

    operations = [
        migrations.AddField(
            model_name='redpropiagrafo',
            name='lineas_originales_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redpropiagrafo',
            name='n_lineas_ajustadas',
            field=models.IntegerField(default=0),
        ),
    ]
