# Generated by Django 6.0.7 on 2026-07-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0010_redpropiagrafo_lineas_originales_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedPropiaCargaProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_progreso', models.BooleanField(default=False)),
                ('lineas_total', models.IntegerField(default=0)),
                ('lineas_hechas', models.IntegerField(default=0)),
                ('mensaje', models.CharField(blank=True, default='', max_length=300)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
