# Generated by Django 6.0.7 on 2026-08-06 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0011_redpropiacargaprogreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='peso_minimo_viaje_extra_kg',
            field=models.PositiveIntegerField(default=0, help_text='Desalienta (no prohíbe) que el 2do/3er viaje de un camión cargue menos que esto -- evita viajes casi vacíos a descargar. 0 = desactivado.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
