# Generated by Django 6.0.7 on 2026-08-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0012_configuraciongeneral_peso_minimo_viaje_extra_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaRealArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camino_json', models.JSONField(blank=True, null=True)),
                ('camino_original_json', models.JSONField(blank=True, null=True)),
                ('n_lineas', models.IntegerField(default=0)),
                ('ajustado_a_osm', models.BooleanField(default=False)),
                ('saltos_json', models.JSONField(blank=True, default=list)),
                ('distancia_km', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RutaRealProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_progreso', models.BooleanField(default=False)),
                ('lineas_total', models.IntegerField(default=0)),
                ('lineas_hechas', models.IntegerField(default=0)),
                ('mensaje', models.CharField(blank=True, default='', max_length=300)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
