# Generated by Django 6.0.7 on 2026-08-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0013_rutarealarchivo_rutarealprogreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutarealarchivo',
            name='ajustado_a_osm',
        ),
        migrations.AddField(
            model_name='rutarealarchivo',
            name='n_tramos_ajustados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rutarealarchivo',
            name='n_tramos_total',
            field=models.IntegerField(default=0),
        ),
    ]
