# Generated by Django 6.0.7 on 2026-08-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0014_remove_rutarealarchivo_ajustado_a_osm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutarealarchivo',
            name='camino_json',
        ),
        migrations.RemoveField(
            model_name='rutarealarchivo',
            name='camino_original_json',
        ),
        migrations.RemoveField(
            model_name='rutarealarchivo',
            name='distancia_km',
        ),
        migrations.RemoveField(
            model_name='rutarealarchivo',
            name='n_tramos_ajustados',
        ),
        migrations.RemoveField(
            model_name='rutarealarchivo',
            name='n_tramos_total',
        ),
        migrations.RemoveField(
            model_name='rutarealarchivo',
            name='saltos_json',
        ),
        migrations.AddField(
            model_name='rutarealarchivo',
            name='rutas_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
