# Generated by Django 6.0.7 on 2026-08-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0015_remove_rutarealarchivo_camino_json_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedPropiaResultado',
        ),
        migrations.RemoveField(
            model_name='redpropiagrafo',
            name='aristas_json',
        ),
        migrations.RemoveField(
            model_name='redpropiagrafo',
            name='lineas_originales_json',
        ),
        migrations.RemoveField(
            model_name='redpropiagrafo',
            name='n_componentes',
        ),
        migrations.RemoveField(
            model_name='redpropiagrafo',
            name='n_lineas',
        ),
        migrations.RemoveField(
            model_name='redpropiagrafo',
            name='n_lineas_ajustadas',
        ),
        migrations.RemoveField(
            model_name='redpropiagrafo',
            name='nodos_json',
        ),
        migrations.RemoveField(
            model_name='redpropiagrafo',
            name='tamano_componentes_json',
        ),
        migrations.AddField(
            model_name='redpropiagrafo',
            name='zonas_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
