# Generated by Django 6.0.7 on 2026-08-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0016_delete_redpropiaresultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redpropiacargaprogreso',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
