# Generated by Django 6.0.7 on 2026-08-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0017_redpropiacargaprogreso_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaRealCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('n_lineas', models.IntegerField(default=0)),
                ('rutas_json', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.DeleteModel(
            name='RutaRealArchivo',
        ),
    ]
