# Generated by Django 6.0.7 on 2026-08-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0018_rutarealcarga_delete_rutarealarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='franjas_trafico',
            field=models.JSONField(blank=True, default=list, help_text="Franjas horarias de tráfico típico (ej. hora pico), configuradas a mano en vez de depender de un servicio de tráfico en vivo (que suele ser pago). Lista de {'inicio': 'HH:MM', 'fin': 'HH:MM', 'multiplicador': float}; multiplicador < 1 representa más lento (tráfico)."),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='usar_franjas_trafico',
            field=models.BooleanField(default=False),
        ),
    ]
